function [feature,location]=ExtractFeature(audioVect,Fs,windowlength,overlaplength)
[feature,location] = pitch(audioVect,Fs, ...
    'WindowLength',windowlength, ...
    'OverlapLength',overlaplength, ...
    'Range',[50 400], ...
    'MedianFilterLength',3);
end